language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - psql -c 'create database store_manager;' -U postgres
  - psql -c "create user kamar with password 'pass@word1' createdb;" -U postgres
  - python app/database.py


# command to run tests
script:
  - pytest --cov
branches:
  only:
  - ch-tests-set-up-161443803
  - ft-writing-tests-setting-up-161443803
  - develop
  - master
  - challenge3
after_success:
  - coveralls