language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - psql -c 'create database store_manager;' -U postgres
  - psql -c "create user kamar with password 'pass@word1' createdb;" -U postgres
  - python app/database.py


# command to run tests
script:
  - pytest --cov
branches:
  only:
  - ch-tests-set-up-161443803
  - ft-writing-tests-setting-up-161443803
  - develop
  - master
  - challenge3
after_success:
  - coveralls

env:
  - FLASK_CONFIG='development'
  - DATABASE_URL='postgres://hpwkkcsgckkgvk:2e5282386e7f2a3e1faef5558102a71b67019dc02844d1b16a5374b8e354be7a@ec2-107-22-189-136.compute-1.amazonaws.com:5432/d4501hveeam6gl'